server:
  port: 9595
spring:
  datasource:
    username: system
    password: system
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/XE
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: noreplyjrtp@gmail.com
    password: Jrtp@0018
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  